package websocket

const (
	OPCODE_CONTINUATION = 0x0
	OPCODE_TEXT         = 0x1
	OPCODE_BINARY       = 0x2
	OPCODE_CLOSE        = 0x8
	OPCODE_PING         = 0x9
	OPCODE_PONG         = 0xA
)

const (
	STATUS_CODE_NORMAL_CLOSURE             = 1000
	STATUS_CODE_GOING_AWAY                 = 1001
	STATUS_CODE_PROTOCOL_ERROR             = 1002
	STATUS_CODE_UNSUPPORTED_DATA_TYPE      = 1003
	STATUS_CODE_RESERVED                   = 1004
	STATUS_CODE_NO_STATUS_CODE_PRESENT     = 1005
	STATUS_CODE_ABNORMAL_CLOSURE           = 1006
	STATUS_CODE_INVALID_FRAME_PAYLOAD_DATA = 1007
	STATUS_CODE_POLICY_VIOLATION           = 1008
	STATUS_CODE_MESSAGE_TOO_BIG            = 1009
	STATUS_CODE_MANDATORY_EXTENSION        = 1010
	STATUS_CODE_INTERNAL_SERVER_ERROR      = 1011
	STATUS_CODE_TLS_HANDSHAKE              = 1015
)
